blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, ContactView

urlpatterns = [
    path('contacts/', ContactView.as_view(template_name='blog/contacts.html'), name='contacts'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_form'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog_detail'),

    path('blog/<str:slug>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<str:slug>/delete/', BlogDeleteView.as_view(template_name='blog/blog_confirm_delete.html'), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blog

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
                  path('message/', include(('message.urls', 'message'), namespace='message')),
                  path('', include(('mailing.urls', 'mailing'), namespace='mailing')),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path("__debug__/", include(debug_toolbar.urls)),
                  ] + urlpatterns

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import *


urlpatterns = [
    path('', HomeView.as_view(template_name='mailing/home.html'), name='home'),
    # mailing
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/delete/<int:pk>/', cache_page(60)(MailingDeleteView.as_view()), name='mailing_delete'),
    path('toggle/<int:pk>/', toggle_status, name='toggle_status'),
    # clients
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/detail/<int:pk>/', cache_page(60)(ClientDetailView.as_view()), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    # mailing_log
    path('mailing_log/', MailingLogListView.as_view(), name='mailing_log_list'),
]

mailing/models.py
from django.db import models

from config import settings
from message.models import Message

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """Модель клиента"""
    name = models.CharField(max_length=150, verbose_name='Фамилия Имя Отчество')
    email = models.EmailField(unique=True, verbose_name='Почта')
    message = models.TextField(verbose_name='Комментарий', **NULLABLE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Активность')

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'
        ordering = ('name',)

    def __str__(self):
        return f"{self.name} ({self.email})"

    def delete(self, *args, **kwargs):
        """Функция, делающая пользователя не активным"""
        self.is_active = False
        self.save()




class Mailing(models.Model):
    """Модель рассылки"""

    FREQUENCY = [
        ('DAY', 'раз в день'),
        ('WEEK', 'раз в неделю'),
        ('MONTH', 'раз в месяц')
    ]

    STATUS = [
        ('FINISH', 'завершена'),
        ('CREATE', 'создана'),
        ('START', 'запущена')
    ]

    time = models.TimeField(auto_now_add=True, verbose_name='Время рассылки')
    create_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    frequency = models.CharField(max_length=100, choices=FREQUENCY, verbose_name='Периодичность')
    status = models.CharField(max_length=100, choices=STATUS, verbose_name='Статус')
    client = models.ManyToManyField(Client, verbose_name='Клиент', blank=True)
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, verbose_name='Сообщение', **NULLABLE)
    finish_date = models.DateField(verbose_name='Дата завершения рассылки', default='2024-01-01')
    finish_time = models.TimeField(verbose_name='Время завершения рассылки', default='00:00')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='Опубликован')

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ('time',)

    def __str__(self):
        return f'Рассылка №{self.pk}'

    def delete(self, *args, **kwargs):
        """Функция, делающая пост не активным"""
        self.is_published = False
        self.status = 'FINISH'
        self.save()


class MailingLogs(models.Model):
    """Модель логов рассылки"""
    STATUS = [
        ('Success', 'успешно'),
        ('Failure', 'отказ')
    ]

    data_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')
    status = models.CharField(max_length=100, choices=STATUS, verbose_name='Статус попытки')
    server_response = models.TextField(verbose_name='Ответ почтового сервера', **NULLABLE)
    mailing = models.ForeignKey(Mailing, on_delete=models.SET_NULL, verbose_name='Рассылка', **NULLABLE)

    class Meta:
        verbose_name = 'лог отправки письма'
        verbose_name_plural = 'логи отправок писем'

    def __str__(self):
        return f'Лог {self.pk}'

mailing/forms.py
from django import forms

from mailing.models import Client, Mailing, Message


class FormStyleMixin:
    """Класс-миксин для стилизации форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(FormStyleMixin, forms.ModelForm):
    """Форма для создания и редактирования поста"""

    class Meta:
        model = Client
        exclude = ('is_active', 'user')


class MailingForm(FormStyleMixin, forms.ModelForm):
    """Форма для создания и редактирования рассылки"""

    class Meta:
        model = Mailing
        exclude = ('is_active', 'user', 'status', 'is_published')


class MessageForm(FormStyleMixin, forms.ModelForm):
    """Форма для создания и редактирования сообщения"""

    class Meta:
        model = Message
        exclude = ('header', 'body')

mailing/views.py
from random import sample

from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView, TemplateView

from blog.models import Blog
from mailing.forms import ClientForm, MailingForm, MessageForm
from mailing.models import *
from mailing.services.services import MessageService, delete_task, send_mailing, get_count_mailing, get_active_mailing, \
    get_unique_clients


class HomeView(TemplateView):
    """Представление главной страницы сервиса"""
    extra_context = {
        'title': 'SkyBlog'
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_posts = list(Blog.objects.all())
        context['random_post'] = sample(all_posts, min(3, len(all_posts)))
        context['count_mailing'] = get_count_mailing()
        context['active_mailing'] = get_active_mailing()
        context['unique_clients'] = get_unique_clients()

        return context


############################-Mailing-#################################

class MailingListView(LoginRequiredMixin, ListView):
    """Представление для просмотра рассылок"""
    model = Mailing
    form_class = MailingForm
    extra_context = {'title': 'Рассылки'}

    def get_queryset(self):
        """Функция, позволяющая просматривать только свои рассылки для пользователя, который не является менеджером"""
        user = self.request.user
        if user.is_superuser or user.is_staff:
            queryset = Mailing.objects.all()
        else:
            queryset = Mailing.objects.filter(user=user)

        queryset = queryset.filter(is_published=True)
        return queryset


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Представление для создания рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_queryset(self):
        user = self.request.user
        mailing = Mailing.objects.all()
        if user.is_staff or user.is_superuser:
            queryset = mailing
        else:
            queryset = mailing.client.filter(user=user)
        return queryset

    def form_valid(self, form):
        """Если форма валидна, то при создании рассылки запускается периодическая задача и изменяется статус рассылки"""
        mailing = form.save(commit=False)
        mailing.user = self.request.user
        mailing.status = 'CREATE'
        mailing.save()

        message_service = MessageService(mailing)
        send_mailing(mailing)
        message_service.create_task()
        mailing.status = 'START'
        mailing.save()

        return super(MailingCreateView, self).form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Представление для изменения рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    """Представление для удаления рассылки"""
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')


def toggle_status(request, pk):
    """Функция, позволяющая отключать и активировать рассылку"""
    mailing = get_object_or_404(Mailing, pk=pk)
    message_service = MessageService(mailing)
    if mailing.status == 'START' or mailing.status == 'CREATE':
        delete_task(mailing)
        mailing.status = 'FINISH'
    else:
        message_service.create_task()
        mailing.status = 'START'

    mailing.save()

    return redirect(reverse('mailing:mailing_list'))


############################-Message-#################################


# class MessageListView(LoginRequiredMixin, ListView):
#     """Представление для просмотра сообщений"""
#     model = Message
#     form_class = MessageForm
#     extra_context = {'title': 'Сообщения'}
#
#     def get_queryset(self):
#         """Функция, позволяющая просматривать только свои сообщения для пользователя, который не является менеджером"""
#         user = self.request.user
#         if user.is_superuser or user.is_staff:
#             queryset = Message.objects.all()
#         else:
#             queryset = Message.objects.filter(user=user)
#
#         queryset = queryset.filter(is_published=True)
#         return queryset
#
#
# class MessageDetailView(LoginRequiredMixin, DetailView):
#     """Представление для просмотра конкретного сообщения"""
#     model = Message
#
#
# # class MessageCreateView(LoginRequiredMixin, CreateView):
# #     """Представление для создания сообщения"""
# #     model = Message
# #     form_class = MessageForm
# #     success_url = reverse_lazy('message:message_list')
#
# class MessageCreateView(LoginRequiredMixin, CreateView):
#     """Представление для создания сообщения"""
#     model = Message
#     fields = ('header', 'body', 'user')
#     success_url = reverse_lazy('message:message_list')
#
#     # def __init__(self, **kwargs):
#     #     super().__init__(**kwargs)
#     #     self.object = None
#
#
# class MessageUpdateView(LoginRequiredMixin, UpdateView):
#     """Представление для изменения сообщения"""
#     model = Message
#     form_class = MessageForm
#     success_url = reverse_lazy('message:message_list')
#
#
# class MessageDeleteView(LoginRequiredMixin, DeleteView):
#     """Представление для удаления сообщения"""
#     model = Message
#     success_url = reverse_lazy('message:message_list')


############################-Client-#################################

class ClientListView(LoginRequiredMixin, ListView):
    """Представление для просмотра клиентов"""
    model = Client
    extra_context = {'title': 'Клиенты'}

    def get_queryset(self):
        """Функция, позволяющая просматривать только своих клиентов для пользователя, который не является менеджером"""
        user = self.request.user
        if user.is_staff or user.is_superuser:
            queryset = Client.objects.all()
        else:
            queryset = Client.objects.filter(user=user)

        queryset = queryset.filter(is_active=True)
        return queryset


class ClientDetailView(LoginRequiredMixin, DetailView):
    """Представление для просмотра конкретного клиента"""
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Представление для создания клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        client = form.save(commit=False)
        client.user = self.request.user
        client.save()
        return super(ClientCreateView, self).form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """Представление для изменения клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')


class ClientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """Представление для удаления клиента"""
    model = Client
    success_url = reverse_lazy('mailing:client_list')
    permission_required = 'mailing.delete_client'


############################-MailingLogs-#################################

class MailingLogListView(LoginRequiredMixin, ListView):
    """Представление для просмотра всех попыток рассылок"""
    model = MailingLogs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Попытки рассылки"
        context['log_list'] = MailingLogs.objects.all()
        return context

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
{% include 'mailing/includes/inc_blog_menu.html' %}

{% block content %}
{% endblock %}

<footer class="text-muted">
    <div class="container">
        <p>&copy; {% now 'Y' %} </p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
{#
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
#}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            Уверены что хотите заблокировать клиента {{ client.name }}
            <input type="submit" class="btn btn-success" value="Уверен">
        </div>
    </form>
    <a href="{% url 'mailing:client_list' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
<div class="table">
    <table>
        <tr>
            <h2>{{ client.name }}</h2>
            <h3>{{client.email}}</h3>
        </tr>
    </table>
</div>

{% if client.user == user %}
<div class="container">
    <a href='{% url "mailing:client_update" client.pk %}' class="btn btn-secondary my-3"
       style="background: darkgreen">Изменить</a>

    {% endif %}

    {% if perms.mailing.delete_client or client.user == user %}
    <a href='{% url "mailing:client_delete" client.pk %}' class="btn btn-secondary my-3"
       style="background: red">Заблокировать</a>
</div>
{% endif %}

<div class="container">
    <a href='{% url "mailing:client_list" %}' class="btn btn-secondary my-3"
       style="background: blue">Назад</a>
</div>

{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            {{ form.as_p }}
            <input type="submit" class="btn btn-success" value="Сохранить">
        </div>
    <a href="{% url 'mailing:client_list' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
    </form>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
<div class="table">
    <table>
        {% for client in client_list %}
        <tr>
            <td>
                <a style="color: black" class="btn" href="{% url 'mailing:client_detail' client.pk %}">
                    {{ client.name }}</a>
            </td>
            <td>
                {{client.email}}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

<div class="container">
    <a href='{% url "mailing:client_create" %}' class="btn btn-secondary my-3"
       style="background: darkgreen">Добавить</a>
</div>

{% endblock %}

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
<div class="table">
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table>
                        <tr>
                            <td>
                                Количество рассылок всего
                            </td>
                            <td>
                                {{count_mailing}}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Количество активных рассылок:
                            </td>
                            <td>
                                {{active_mailing}}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Количество уникальных клиентов для рассылок:
                            </td>
                            <td>
                                {{unique_clients}}
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% for object in blog_list %}
<div class="row">
    <div class="col-lg-4">
        <img class="rounded-circle"
             src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
             alt="Generic placeholder image" width="150" height="150">
        <h2>{{ object.title }}</h2>
        <p>{{ object.text}}.</p>
        <p><a class="btn btn-secondary" href="{% url 'blog:blog_detail' object.slug %}" role="button">Смотреть больше
            &raquo;</a></p>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            Уверены что хотите удалить рассылку {{ mailing }}
            <input type="submit" class="btn btn-success" value="Уверен">
        </div>
    </form>
    <a href="{% url 'mailing:mailing_list' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}

<div class="card">
    <h1>{{ object.mail_title }}</h1>
    <p class="price">{{ object.slug }}</p>
    <p>{{ object.mail_text }}</p>
</div>
<h5 style="color:#FF0000">{{ object.view_count }}</h5>
<a class="btn btn-warning" href="{% url 'mailing:mailing_update' object.pk %}" role="button">Изменить
</a> <br>
<a class="btn btn-danger" href="{% url 'mailing:mailing_delete' object.pk %}" role="button">Удалить
</a> <br>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
<form class="obratnuj-zvonok" autocomplete="off" method='post'>
    {% csrf_token %}
    <div class="container">
        {{ form.as_p }}
        {% if user.is_authenticated%}
        <input type="submit" class="btn btn-success" value="Сохранить">
        {% endif %}
    </div>
    <a href="{% url 'mailing:mailing_list' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
</form>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
{% for mailing in mailing_list %}
<div class="my-3 p-3 bg-white rounded box-shadow">

    {% if mailing.user == user or user.is_superuser %}
    <a href="{% url 'mailing:mailing_update' mailing.pk %}" class="border-bottom border-gray pb-2 mb-0">
        {{ mailing }}</a>
    {% else %}
    <a href="#" class="border-bottom border-gray pb-2 mb-0">{{ mailing }}</a>
    {% endif %}

    <div class="media text-muted pt-3">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">Периодичность: {{ mailing.frequency }}</strong>
            <strong class="d-block text-gray-dark">Статус: {{ mailing.status }}</strong>
        </p>
    </div>

    {% if user.is_staff or user == mailing.user %}
    <a href="{% url 'mailing:mailing_delete' mailing.pk %}" class="btn btn-secondary"
       style="background: red">Удалить</a>
    {% endif %}

    {% if user.is_staff or user == mailing.user %}
    <a href="{% url 'mailing:toggle_status' mailing.pk %}" class="btn btn-secondary"
       style="background: blue">
        {% if mailing.status == 'FINISH' %}
        Активировать
        {% else %}
        Отключить
        {% endif %}
    </a>
    {% endif %}
</div>
{% endfor %}

{% if user.is_authenticated %}
<div class="container">
    <a href="{% url 'mailing:mailing_create' %}" class="btn btn-secondary my-3"
       style="background: darkgreen">Создать</a>
{% endif %}
</div>
{% endblock %}

mailing/templates/mailing/mailinglogs_list.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
<div class="table">
    <table>
        <tr>
            <td>
                Время рассылки
            </td>
            <td>
                Рассылка
            </td>
            <td>
                Статус
            </td>
        </tr>
        {% for log in log_list %}
        <tr>
            <td>
                {{ log.data_time }}
            </td>
            <td>
                {{log.mailing}}
            </td>
            <td>
                {{ log.status }}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}