blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, ContactView

urlpatterns = [
    path('contacts/', ContactView.as_view(template_name='blog/contacts.html'), name='contacts'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_form'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog_detail'),

    path('blog/<str:slug>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<str:slug>/delete/', BlogDeleteView.as_view(template_name='blog/blog_confirm_delete.html'), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blog

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
                  path('message/', include(('message.urls', 'message'), namespace='message')),
                  path('', include(('mailing.urls', 'mailing'), namespace='mailing')),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path("__debug__/", include(debug_toolbar.urls)),
                  ] + urlpatterns

blog/models.py
import uuid

from django.db import models
from django.template.defaultfilters import slugify
from django.utils.text import slugify

NULLABLE = {'blank': True, 'null': True}


class Contacts(models.Model):
    contact_text = models.TextField(verbose_name='контакты', **NULLABLE)

    def __str__(self):
        return 'Контакты'


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(verbose_name='slug', max_length=255, unique=True)
    text = models.TextField(verbose_name='содержимое', **NULLABLE)
    image = models.ImageField(upload_to='blog_image/', verbose_name='изображение', **NULLABLE)
    date = models.DateField(verbose_name='дата создания', auto_now_add=True, **NULLABLE)
    view_count = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True, verbose_name='публикация')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            while Blog.objects.filter(slug=self.slug).exists():
                self.slug = f"{self.slug}-{uuid.uuid4().hex[:6]}"
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'
        ordering = ('view_count',)

blog/forms.py
from django import forms
from django.conf import settings

from blog.models import Blog


class MixinStyle:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BlogForms(MixinStyle, forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ('is_active', 'date_create')

    def clean_product_name(self):
        cleaned_name = self.cleaned_data['product_name']
        for word in settings.FORBIDDEN_WORDS:
            if word in cleaned_name:
                raise forms.ValidationError(f'Запрещено использовать слово {word}.')
            if word.title() in cleaned_name:
                raise forms.ValidationError(f'Запрещено использовать слово {word}.')
        return cleaned_name

    def clean_product_text(self):
        cleaned_text = self.cleaned_data['product_text']
        for word in settings.FORBIDDEN_WORDS:
            if word.title() in cleaned_text:
                raise forms.ValidationError(f'Запрещено использовать слово {word}.')
            if word in cleaned_text:
                raise forms.ValidationError(f'Запрещено использовать слово {word}.')
        return cleaned_text

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from blog.forms import BlogForms
from blog.models import Blog, Contacts


class BlogListView(ListView):
    """Представление для просмотра блогов"""
    model = Blog
    form_class = BlogForms
    success_url = reverse_lazy('blog:blog_list')
    template_name = 'blog/blog_list.html'


    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset


class BlogDetailView(LoginRequiredMixin, DetailView):
    """Представление для просмотра конкретного блога"""
    model = Blog
    form_class = BlogForms
    success_url = reverse_lazy('blog:blog_detail')
    template_name = 'blog/blog_detail.html'

    def get_object(self, queryset=None):
        object = super().get_object(queryset=queryset)
        object.view_count += 1
        object.save()
        return object


class BlogCreateView(LoginRequiredMixin, CreateView):
    """Представление для создания блога"""
    model = Blog
    fields = ('title', 'text', 'image', 'is_active')
    success_url = reverse_lazy('blog:blog_list')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    """Представление для изменения блога"""
    model = Blog
    fields = ('title', 'text', 'image', 'is_active')

    def get_success_url(self):
        return reverse('mailing:blog_detail', kwargs={'pk': self.object.pk})


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    """Представление для удаления блога"""
    model = Blog
    success_url = reverse_lazy('mailing:blog_list')


class ContactView(TemplateView):
    """Представление страницы контактов сервиса"""
    model = Contacts

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Уверены что хотите удалить "{{ object }}"? <br>
                    <input type="submit" class="btn btn-danger" value="Вы уверены?">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:blog_list' %}" role="button">Отмена
                    &raquo;</a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}

<div class="card">
    <h1>{{ object.mail_title }}</h1>
    <p class="price">{{ object.slug }}</p>
    <p>{{ object.mail_text }}</p>
</div>
<h5 style="color:#FF0000">{{ object.view_count }}</h5>
<a class="btn btn-warning" href="{% url 'blog:blog_update' slug=object.slug %}" role="button">Изменить
</a> <br>
<a class="btn btn-danger" href="{% url 'blog:blog_delete' slug=object.slug %}" role="button">Удалить
</a> <br>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
<div class="col">
    <div class="card">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-success"
                       value="{% if object %}Сохранить{% else %}Создать{% endif %}">
            </form>
        </div>
        <div class="card-footer">
            <a href="{% url 'blog:blog_list' %}" role="button">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
<div class="container marketing">
    {% for object in blog_list %}
    <div class="row">
        <div class="col-lg-4">
            <img class="rounded-circle"
                 src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                 alt="Generic placeholder image" width="150" height="150">
            <h2>{{ object.title }}</h2>
            <p>{{ object.slug }}</p>
            <p><a class="btn btn-secondary" href="{% url 'blog:blog_detail' object.slug %}" role="button">Смотреть
                &raquo;</a></p>
        </div>
    </div>
    {% endfor %}
    <p><a class="btn btn-secondary" href="{% url 'blog:blog_form' %}" role="button">Создать
    </a></p>
</div>
{% endblock %}

blog/templates/blog/contacts.html
{% extends 'mailing/base.html'%}
{% load mediapath %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}