blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, ContactView

urlpatterns = [
    path('contacts/', ContactView.as_view(template_name='blog/contacts.html'), name='contacts'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_form'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog_detail'),

    path('blog/<str:slug>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<str:slug>/delete/', BlogDeleteView.as_view(template_name='blog/blog_confirm_delete.html'), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blog

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
                  path('message/', include(('message.urls', 'message'), namespace='message')),
                  path('', include(('mailing.urls', 'mailing'), namespace='mailing')),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path("__debug__/", include(debug_toolbar.urls)),
                  ] + urlpatterns

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import *


urlpatterns = [
    path('', HomeView.as_view(template_name='mailing/home.html'), name='home'),
    # mailing
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/delete/<int:pk>/', cache_page(60)(MailingDeleteView.as_view()), name='mailing_delete'),
    path('toggle/<int:pk>/', toggle_status, name='toggle_status'),
    # clients
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/detail/<int:pk>/', cache_page(60)(ClientDetailView.as_view()), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    # mailing_log
    path('mailing_log/', MailingLogListView.as_view(), name='mailing_log_list'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserUpdateView, UserRegisterView, EmailConfirmationSentView, \
    EmailConfirmView, EmailConfirmationFailedView, UserForgotPasswordView, UserPasswordResetConfirmView, \
    PasswordResetSentView, PasswordSuccessSentView, UserConfirmEmailView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),  # войти
    path('logout/', LogoutView.as_view(), name='logout'),  # выйти
    path('register/', UserRegisterView.as_view(), name='register'),  # регистрация
    path('profile/', UserUpdateView.as_view(), name='profile'),  # профиль
    path('email_confirmation_sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', EmailConfirmView.as_view(), name='email_verified'),
    path('confirm_email_failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_sent/', PasswordResetSentView.as_view(), name='password_reset_sent'),
    path('password_success_sent/', PasswordSuccessSentView.as_view(), name='password_success_sent'),
]

users/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models

NULLABLE: dict[str, bool] = {'blank': True, 'null': True}


class CustomUserManager(UserManager):

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")

        email = self.normalize_email(email)
        extra_fields.setdefault('is_active', True)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    avatar = models.ImageField(upload_to='user_avatar/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=150, verbose_name='страна', **NULLABLE)
    is_active = models.BooleanField(default=False)
    token = models.CharField(max_length=200, verbose_name='токен', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'
        ordering = ('email',)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm, SetPasswordForm

from users.models import User


class MixinStyle:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(MixinStyle, UserCreationForm):
    """Регистрация пользователя"""

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')  # пользователя просят ввести 2 раза пароль

    def __init__(self, *args, **kwargs):
        """Обновление стилей формы регистрации"""
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields['email'].widget.attrs.update({"placeholder": 'Введите email'})
            self.fields['password1'].widget.attrs.update({"placeholder": 'Придумайте пароль'})
            self.fields['password2'].widget.attrs.update({"placeholder": 'Повторите пароль'})
            self.fields[field].widget.attrs.update({"class": "form-control", "autocomplete": "off"})


class UserProfileForm(MixinStyle, UserChangeForm):
    """Класс профиль"""

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        """Обновление стилей формы профиль"""
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields['email'].widget.attrs.update({"placeholder": 'Введите свой email'})
            self.fields['first_name'].widget.attrs.update({"placeholder": 'Ваше имя'})
            self.fields["last_name"].widget.attrs.update({"placeholder": 'Ваша фамилия'})
            self.fields[field].widget.attrs.update({"class": "form-control", "autocomplete": "off"})
            self.fields['password'].widget = forms.HiddenInput()  # убирает поле пароль


class UserForgotPasswordForm(PasswordResetForm):
    """
    Запрос на восстановление пароля
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class UserSetNewPasswordForm(SetPasswordForm):
    """
    Изменение пароля пользователя после подтверждения
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin

from django.core.mail import send_mail
from django.shortcuts import redirect

from users.models import User
from django.urls import reverse_lazy

from django.views import View
from django.views.generic import UpdateView, CreateView, TemplateView
from django.conf import settings

from users.forms import UserRegisterForm, UserProfileForm, UserForgotPasswordForm, UserSetNewPasswordForm
from users.services.services import auth_send_mail


class UserRegisterView(CreateView):
    """Класс региcтрации пользователя"""
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Вы успешно зарегистрировались. Проверьте почту для активации!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация на сайте'
        return context

    def form_valid(self, form):
        user = form.save(commit=False)
        send_mail(
            subject='Вы зарегистрировались!',
            message='Спасибо за регистрацию на нашей платформе',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        user.is_active = False
        user.token = default_token_generator.make_token(user)
        activation_url = reverse_lazy(
            'users:confirm_email', kwargs={'token': user.token}
        )
        auth_send_mail(user.email, activation_url)
        user.save()
        return redirect('users:email_confirmation_sent')


class UserConfirmEmailView(View):
    def get(self, request, token):
        try:
            user = User.objects.get(token=token)
        except User.DoesNotExist:
            return redirect('users:email_confirmation_failed')

        user.is_active = True
        user.token = None
        user.save()
        return redirect('users:email_verified')


class EmailConfirmationSentView(TemplateView):
    template_name = 'users/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class EmailConfirmView(TemplateView):
    template_name = 'users/email_verified.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context


class EmailConfirmationFailedView(TemplateView):
    template_name = 'users/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')
    template_name = 'users/user_form.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Страница пользователя: {self.object.email}'
        return context


class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """
    Представление по сбросу пароля по почте
    """
    form_class = UserForgotPasswordForm
    template_name = 'users/user_password_reset.html'
    success_url = reverse_lazy('users:password_reset_sent')
    success_message = 'Письмо с инструкцией по восстановлению пароля отправлена на ваш email'
    subject_template_name = 'users/email/password_subject_reset_mail.txt'
    email_template_name = 'users/email/password_reset_mail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запрос на восстановление пароля'
        return context


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """
    Представление установки нового пароля
    """
    form_class = UserSetNewPasswordForm
    template_name = 'users/user_password_set_new.html'
    success_url = reverse_lazy('users:password_success_sent')
    success_message = 'Пароль успешно изменен. Можете авторизоваться на сайте.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Установить новый пароль'
        return context


class PasswordResetSentView(TemplateView):
    template_name = 'users/password_reset_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class PasswordSuccessSentView(TemplateView):
    template_name = 'users/password_success_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Вы сменили пароль'
        return context

users/templates/users/email_confirmation_failed.html
{% extends 'mailing/base.html' %}
{% block content %}

    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Ошибка подтверждения по электронной почте</h4>
        <p>Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек. Пожалуйста,
            зарегистрируйтесь снова.</p>
    </div>

{% endblock %}

users/templates/users/email_confirmation_sent.html
{% extends 'mailing/base.html' %}
{% block content %}

    <div class="alert alert-info" role="alert">
        <h4 class="alert-heading">Письмо подтверждения отправлено!</h4>
        <p>
            На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте свою
            электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
            Если письмо не пришло, проверьте папку спам.
        </p>
    </div>

{% endblock %}

users/templates/users/email_verified.html
{% extends 'mailing/base.html' %}
{% block content %}

    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Электронная почта подтверждена</h4>
        <p>Ваш адрес электронной почты успешно подтвержден. Спасибо за регистрацию! Можете войти на сайт</p>
    </div>
     <a class="btn btn-outline-primary" href="{% url 'mailing:home' %}" role="button">Вернуться на главную
                </a> <br>
{% endblock %}

users/templates/users/login.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="Войти">
                </form>
                <a href="{% url 'users:password_reset' %}" role="button">Забыли пароль?
                    </a>
            </div>
            <div class="card-footer">
                <a href="{% url 'mailing:home' %}" role="button">Назад
                    </a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset_sent.html
{% extends 'mailing/base.html' %}
{% block content %}

    <div class="alert alert-info" role="alert">
        <h4 class="alert-heading">Письмо c новым паролем отправлено!</h4>
        <p>
            На ваш адрес электронной почты было отправлено письмо. Пожалуйста, проверьте свою
            электронную почту и нажмите на ссылку, чтобы сменить пароль.
            Если письмо не пришло, проверьте папку спам.
        </p>
    </div>

{% endblock %}

users/templates/users/password_success_sent.html
{% extends 'mailing/base.html' %}
{% block content %}

    <div class="alert alert-info" role="alert">
        <h4 class="alert-heading">Вы успешно сменили пароль!</h4>
        <p>
            Ваш пароль был обновлен. Теперь вы можете авторизоваться.
        </p>
        <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        </nav>
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="{% if object %}Сохранить{% else %}Создать{% endif %}">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'mailing:home' %}" role="button">Назад
                    &raquo;</a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="Сохранить">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'mailing:home' %}" role="button">Назад
                    &raquo;</a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Запрос на восстановление пароля на сайте</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Восстановить пароль</button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/user_password_set_new.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Установить новый пароль</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Подтвердить</button>
            </form>
        </div>
    </div>
{% endblock %}