blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, ContactView

urlpatterns = [
    path('contacts/', ContactView.as_view(template_name='blog/contacts.html'), name='contacts'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_form'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog_detail'),

    path('blog/<str:slug>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<str:slug>/delete/', BlogDeleteView.as_view(template_name='blog/blog_confirm_delete.html'), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blog

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
                  path('message/', include(('message.urls', 'message'), namespace='message')),
                  path('', include(('mailing.urls', 'mailing'), namespace='mailing')),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path("__debug__/", include(debug_toolbar.urls)),
                  ] + urlpatterns

message/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page


from mailing.views import *
from message.apps import MessageConfig
from message.views import MessageListView, MessageCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView
app_name = MessageConfig.name

urlpatterns = [

    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/detail/<int:pk>/', cache_page(60)(MessageDetailView.as_view()), name='message_detail'),
    path('message/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', cache_page(60)(MessageDeleteView.as_view()), name='message_delete'),

]

message/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Message(models.Model):
    """Модель сообщения для рассылки"""
    header = models.CharField(max_length=100, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Тело письма')
    is_published = models.BooleanField(default=True, verbose_name='Создано')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'
        ordering = ('header',)

    def __str__(self):
        return self.header

message/views.py
from random import sample

from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView, TemplateView

from blog.models import Blog
from mailing.forms import ClientForm, MailingForm, MessageForm
from mailing.models import *
from mailing.services.services import MessageService, delete_task, send_mailing, get_count_mailing, get_active_mailing, \
    get_unique_clients
from message.models import Message


class MessageListView(LoginRequiredMixin, ListView):
    """Представление для просмотра сообщений"""
    model = Message
    form_class = MessageForm
    extra_context = {'title': 'Сообщения'}

    def get_queryset(self):
        """Функция, позволяющая просматривать только свои сообщения для пользователя, который не является менеджером"""
        user = self.request.user
        if user.is_superuser or user.is_staff:
            queryset = Message.objects.all()
        else:
            queryset = Message.objects.filter(user=user)

        queryset = queryset.filter(is_published=True)
        return queryset


class MessageDetailView(LoginRequiredMixin, DetailView):
    """Представление для просмотра конкретного сообщения"""
    model = Message


# class MessageCreateView(LoginRequiredMixin, CreateView):
#     """Представление для создания сообщения"""
#     model = Message
#     form_class = MessageForm
#     success_url = reverse_lazy('message:message_list')

class MessageCreateView(LoginRequiredMixin, CreateView):
    """Представление для создания сообщения"""
    model = Message
    fields = ('header', 'body', 'user')
    success_url = reverse_lazy('message:message_list')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """Представление для изменения сообщения"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('message:message_list')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """Представление для удаления сообщения"""
    model = Message
    success_url = reverse_lazy('message:message_list')

message/templates/message/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SkyBlog</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'message/includes/inc_blog_menu.html' %}

{% block content %}
{% endblock %}

<footer class="text-muted">
    <div class="container">
        <p>&copy; {% now 'Y' %} </p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
{#<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>#}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

message/templates/message/home.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
<div class="table">
    <table>
        <tr>
            <td>
                Количество рассылок всего
            </td>
            <td>
                {{count_mailing}}
            </td>
        </tr>
        <tr>
            <td>
                Количество активных рассылок:
            </td>
            <td>
                {{active_mailing}}
            </td>
        </tr>
        <tr>
            <td>
                Количество уникальных клиентов для рассылок:
            </td>
            <td>
                {{unique_clients}}
            </td>
        </tr>
    </table>
</div>
{% for object in blog_list %}
<div class="row">
    <div class="col-lg-4">
        <img class="rounded-circle"
             src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
             alt="Generic placeholder image" width="150" height="150">
        <h2>{{ object.title }}</h2>
        <p>{{ object.text}}.</p>
        <p><a class="btn btn-secondary" href="{% url 'message:message_detail' object.slug %}" role="button">Смотреть больше
            &raquo;</a></p>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}

message/templates/message/message_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            Уверены что хотите удалить сообщение {{ message }}
            <input type="submit" class="btn btn-success" value="Уверен">
        </div>
    </form>
    <a href="{% url 'message:message_list' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
{% endblock %}

message/templates/message/message_detail.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}

<div class="card">
    <h1>{{ object.mail_title }}</h1>
    <p class="price">{{ object.slug }}</p>
    <p>{{ object.mail_text }}</p>
</div>
<h5 style="color:#FF0000">{{ object.view_count }}</h5>
<a class="btn btn-warning" href="{% url 'message:message_update' pk=object.pk %}" role="button">Изменить
</a> <br>
<a class="btn btn-danger" href="{% url 'message:message_delete' pk=object.pk %}" role="button">Удалить
</a> <br>
{% endblock %}

message/templates/message/message_form.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
<form class="obratnuj-zvonok" autocomplete="off" method='post'>
    {% csrf_token %}
    <div class="container">
        {{ form.as_p }}
        {% if user.is_authenticated%}
        <input type="submit" class="btn btn-success" value="Сохранить">
        {% endif %}
    </div>
    <a href="{% url 'message:message_list' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
</form>
{% endblock %}

message/templates/message/message_list.html
{% extends 'mailing/base.html' %}
{% load mediapath %}
{% block content %}
{% for message in message_list %}
<div class="my-3 p-3 bg-white rounded box-shadow">

    {% if mailing.user == user or user.is_superuser %}
    <a href="{% url 'message:message_update' message.pk %}" class="border-bottom border-gray pb-2 mb-0">
        {{ message }}</a>
    {% else %}
    <a href="#" class="border-bottom border-gray pb-2 mb-0">{{ message }}</a>
    {% endif %}

    <div class="media text-muted pt-3">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">Тема письма: {{ message.header }}</strong>
            <strong class="d-block text-gray-dark">Содержание: {{ message.body }}</strong>
        </p>
    </div>

    {% if user.is_staff or user == mailing.user %}
    <a href="{% url 'message:message_delete' message.pk %}" class="btn btn-secondary"
       style="background: red">Удалить</a>
    {% endif %}
    </div>
{% endfor %}

{% if user.is_authenticated %}
<div class="container">
    <a href="{% url 'message:message_create' %}" class="btn btn-secondary my-3"
       style="background: darkgreen">Создать</a>
{% endif %}
</div>
{% endblock %}